
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LTE = 30;
  public static final int UMINUS = 50;
  public static final int COMMENT = 43;
  public static final int INTEGER = 46;
  public static final int LPAREN = 6;
  public static final int CONTINUE = 18;
  public static final int INT = 44;
  public static final int MINUS = 3;
  public static final int STATIC = 38;
  public static final int RPAREN = 7;
  public static final int SEMICOLON = 37;
  public static final int LT = 29;
  public static final int COMMA = 12;
  public static final int CLASS = 11;
  public static final int PLUS = 2;
  public static final int QUOTE = 49;
  public static final int ASSIGN = 8;
  public static final int IF = 21;
  public static final int THIS = 39;
  public static final int ID = 47;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 36;
  public static final int LAND = 22;
  public static final int EQUAL = 16;
  public static final int TRUE = 40;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int LOR = 28;
  public static final int NULL = 33;
  public static final int MOD = 31;
  public static final int BREAK = 10;
  public static final int VOID = 41;
  public static final int GTE = 20;
  public static final int LBRACK = 23;
  public static final int TIMES = 4;
  public static final int LBRACE = 24;
  public static final int ELSE = 14;
  public static final int RBRACK = 34;
  public static final int WHILE = 42;
  public static final int NEQUAL = 32;
  public static final int CLASS_ID = 48;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 17;
  public static final int STRING = 45;
  public static final int LNEG = 27;
  public static final int FALSE = 15;
  public static final int GT = 19;
  public static final int LENGTH = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "BOOLEAN",
  "BREAK",
  "CLASS",
  "COMMA",
  "DOT",
  "ELSE",
  "FALSE",
  "EQUAL",
  "EXTENDS",
  "CONTINUE",
  "GT",
  "GTE",
  "IF",
  "LAND",
  "LBRACK",
  "LBRACE",
  "LENGTH",
  "NEW",
  "LNEG",
  "LOR",
  "LT",
  "LTE",
  "MOD",
  "NEQUAL",
  "NULL",
  "RBRACK",
  "RBRACE",
  "RETURN",
  "SEMICOLON",
  "STATIC",
  "THIS",
  "TRUE",
  "VOID",
  "WHILE",
  "COMMENT",
  "INT",
  "STRING",
  "INTEGER",
  "ID",
  "CLASS_ID",
  "QUOTE",
  "UMINUS"
  };
}

